services:
  postgres:
    image: postgres:latest
    container_name: BigDatalab2
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: 1234
      POSTGRES_DB: BigDatalab2
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d
      - ./datacsv:/csvdata
    networks:
      - backend

  spark:
    image: bitnami/spark:latest
    container_name: spark
    user: root
    environment:
      - SPARK_MODE=client
      - HOME=/root
      - SPARK_USER_HOME=/root
    volumes:
      - .:/app
      - ./jars:/opt/spark/jars
    working_dir: /app
    command: bash -c "mkdir -p /root/.ivy2/local && tail -f /dev/null"
    depends_on:
      - postgres
      - clickhouse
    networks:
      - backend

  clickhouse:
    image: clickhouse/clickhouse-server:latest
    container_name: clickhouse
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - clickhouse_data:/var/lib/clickhouse
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    networks:
      - backend
	
volumes:
  postgres_data:
  clickhouse_data:

networks:
  backend:
